---
# Source: airbyte/templates/airbyte-db.yaml
apiVersion: v1
kind: Service
metadata:
  name: airbyte-db-svc
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    
    helm.sh/chart: airbyte-0.45.31
    app.kubernetes.io/name: airbyte-db
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    
    app.kubernetes.io/name: airbyte-db
    app.kubernetes.io/instance: airbyte
---
# Source: airbyte/templates/airbyte-db.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airbyte-db
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    
    helm.sh/chart: airbyte-0.45.31
    app.kubernetes.io/name: airbyte-db
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: airbyte-db-svc
  selector:
    matchLabels:
      
      app.kubernetes.io/name: airbyte-db
      app.kubernetes.io/instance: airbyte
  template:
    metadata:
      labels:
        
        app.kubernetes.io/name: airbyte-db
        app.kubernetes.io/instance: airbyte
    spec:
      containers:
        - name: airbyte-db-container
          image: "558355093142.dkr.ecr.us-east-1.amazonaws.com/airbyte-db"
          env:
            - name: POSTGRES_DB
              value: db-airbyte
            - name: POSTGRES_PASSWORD
              value: airbyte
            - name: POSTGRES_USER
              value: airbyte
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: airbyte-volume-db
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: airbyte-volume-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
