---
# Source: airbyte/templates/minio.yaml
apiVersion: v1
kind: Service
metadata:
  name: airbyte-minio-svc
  labels:
    
    helm.sh/chart: airbyte-0.45.31
    app.kubernetes.io/name: airbyte-minio
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    
    app.kubernetes.io/name: airbyte-minio
    app.kubernetes.io/instance: airbyte
---
# Source: airbyte/templates/minio.yaml
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  # This name uniquely identifies the Deployment
  name: airbyte-minio
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    
    helm.sh/chart: airbyte-0.45.31
    app.kubernetes.io/name: airbyte-minio
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      
      app.kubernetes.io/name: airbyte-minio
      app.kubernetes.io/instance: airbyte
  serviceName: airbyte-minio-svc
  volumeClaimTemplates:
      - metadata:
          name: airbyte-minio-pv-claim
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 500Mi
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        
        app.kubernetes.io/name: airbyte-minio
        app.kubernetes.io/instance: airbyte
    spec:
      # Refer to the PVC created earlier
      containers:
        - name: airbyte-minio
          # Pulls the default Minio image from Docker Hub
          image: "558355093142.dkr.ecr.us-east-1.amazonaws.com/airbyte-minio"
          args:
            - server
            - /storage
          env:
            # Minio access key and secret key. This must match the S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY declared in /dev/.env.
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: minio123
          ports:
            - containerPort: 9000
          # Mount the volume into the pod
          volumeMounts:
            - name: airbyte-minio-pv-claim # must match the volume name, above
              mountPath: "/data"
