---
# Source: airbyte/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airbyte-admin
  labels:
    helm.sh/chart: airbyte-0.45.31
    app.kubernetes.io/name: airbyte
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
