---
# Source: airbyte/charts/connector-builder-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-connector-builder-server
  labels:
    helm.sh/chart: connector-builder-server-0.45.31
    app.kubernetes.io/name: connector-builder-server
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: connector-builder-server
      app.kubernetes.io/instance: airbyte
  strategy:
    type: Recreate # Needed due to volume claims
  template:
    metadata:
      labels:
        app.kubernetes.io/name: connector-builder-server
        app.kubernetes.io/instance: airbyte
    spec:
      serviceAccountName: airbyte-admin
      containers:
      - name: airbyte-connector-builder-server
        image: 558355093142.dkr.ecr.us-east-1.amazonaws.com/airbyte-connector-builder-server
        imagePullPolicy: "IfNotPresent"
        env:
        - name: AIRBYTE_VERSION
          valueFrom:
            configMapKeyRef:
              name: airbyte-airbyte-env
              key: AIRBYTE_VERSION
        
        # Values from secret

        # Values from env

        # Values from extraEnv for more compability(if you want to use external secret source or other stuff)
        livenessProbe:
          httpGet:
            path: /v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3

        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits: {}
          requests: {}
        volumeMounts:
      volumes:
