---
# Source: airbyte/charts/connector-builder-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: airbyte-airbyte-connector-builder-server-svc
  labels:
    helm.sh/chart: connector-builder-server-0.45.31
    app.kubernetes.io/name: connector-builder-server
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: connector-builder-server
    app.kubernetes.io/instance: airbyte
