---
# Source: airbyte/charts/webapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: airbyte-airbyte-webapp-svc
  labels:
    helm.sh/chart: webapp-0.45.31
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: airbyte
