---
# Source: airbyte/charts/temporal/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-temporal
  labels:
    helm.sh/chart: temporal-0.45.31
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: airbyte
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temporal
        app.kubernetes.io/instance: airbyte
    spec:
      serviceAccountName: airbyte-admin
      containers:
      - name: airbyte-temporal
        image: 558355093142.dkr.ecr.us-east-1.amazonaws.com/airbyte-temporal
        imagePullPolicy: IfNotPresent
        env:
          - name: AUTO_SETUP
            value: "true"
          - name: DB # The DB engine to use
            value: "postgresql"
          - name: DB_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: airbyte-airbyte-secrets
                key: DATABASE_USER
          - name: POSTGRES_PWD
            valueFrom:
              secretKeyRef:
                name: airbyte-airbyte-secrets
                key: DATABASE_PASSWORD
          - name: POSTGRES_SEEDS
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: DATABASE_HOST
          - name: DYNAMIC_CONFIG_FILE_PATH
            value: "config/dynamicconfig/development.yaml"
        # Values from secret

        # Values from env
        ports:
        - containerPort: 7233
        volumeMounts:
        - name: airbyte-temporal-dynamicconfig
          mountPath: "/etc/temporal/config/dynamicconfig/"
        resources:
          limits: {}
          requests: {}
      volumes:
      - name: airbyte-temporal-dynamicconfig
        configMap:
          name: airbyte-temporal-dynamicconfig
          items:
          - key: development.yaml
            path: development.yaml
