---
# Source: airbyte/charts/temporal/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: airbyte-temporal
  labels:
    helm.sh/chart: temporal-0.45.31
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.44.12"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 7233
    protocol: TCP
    targetPort: 7233
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: airbyte
